export const analog = {
  name: 'analog',
  sounds: [
    {
      name: 'kick',
      sample: './audio/analog/kick.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num1',
      color: 0,
    },
    {
      name: 'snr',
      sample: './audio/analog/snr.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num2',
      color: 1,
    },
    {
      name: 'clp',
      sample: './audio/analog/clp.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num3',
      color: 2,
    },
    {
      name: 'ch',
      sample: './audio/analog/ch.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num4',
      color: 3,
    },
    {
      name: 'oh',
      sample: './audio/analog/oh.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num5',
      color: 4,
    },
    {
      name: 'cym',
      sample: './audio/analog/cym.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num6',
      color: 5,
    },
    {
      name: 'ht',
      sample: './audio/analog/ht.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num7',
      color: 6,
    },
    {
      name: 'mt',
      sample: './audio/analog/mt.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num8',
      color: 7,
    },
    {
      name: 'lt',
      sample: './audio/analog/lt.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num9',
      color: 8,
    },
  ],
};

export const house = {
  name: 'house',
  sounds: [
    {
      name: 'verb kick',
      sample: './audio/house/kick_verb.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num1',
      color: 0,
    },
    {
      name: 'kick',
      sample: './audio/house/kick.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num2',
      color: 1,
    },
    {
      name: 'snr',
      sample: './audio/house/snr.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num3',
      color: 2,
    },
    {
      name: 'shk',
      sample: './audio/house/shk.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num4',
      color: 3,
    },
    {
      name: 'oh',
      sample: './audio/house/oh.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num5',
      color: 4,
    },
    {
      name: 'clp',
      sample: './audio/house/clp.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num6',
      color: 5,
    },
    {
      name: 'voc',
      sample: './audio/house/voc.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num7',
      color: 6,
    },
    {
      name: 'mt',
      sample: './audio/house/mt.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num8',
      color: 7,
    },
    {
      name: 'lt',
      sample: './audio/house/lt.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num9',
      color: 8,
    },
  ],
};

export const lush = {
  name: 'lush',
  sounds: [
    {
      name: 'long kick',
      sample: './audio/lush/kick_long.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num1',
      color: 0,
    },
    {
      name: 'med kick',
      sample: './audio/lush/kick_mid.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num2',
      color: 1,
    },
    {
      name: 'short kick',
      sample: './audio/lush/kick_short.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num3',
      color: 2,
    },
    {
      name: 'ch',
      sample: './audio/lush/ch.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num4',
      color: 3,
    },
    {
      name: 'oh',
      sample: './audio/lush/oh.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num5',
      color: 4,
    },
    {
      name: 'snr',
      sample: './audio/lush/snr.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num6',
      color: 5,
    },
    {
      name: 'tamb',
      sample: './audio/lush/tamb.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num7',
      color: 5,
    },
    {
      name: 'plop',
      sample: './audio/lush/plop.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num8',
      color: 7,
    },
    {
      name: 'clp',
      sample: './audio/lush/clp.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num9',
      color: 8,
    },
  ],
};

export const vinyl = {
  name: 'vinyl',
  sounds: [
    {
      name: 'kick',
      sample: './audio/vinyl/kick.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num1',
      color: 0,
    },
    {
      name: 'kick 2',
      sample: './audio/vinyl/kick2.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num2',
      color: 1,
    },
    {
      name: 'snr',
      sample: './audio/vinyl/snr.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num3',
      color: 2,
    },
    {
      name: 'ch',
      sample: './audio/vinyl/ch.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num4',
      color: 3,
    },
    {
      name: 'oh',
      sample: './audio/vinyl/oh.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num5',
      color: 4,
    },
    {
      name: 'clp',
      sample: './audio/vinyl/clp.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,

      key: 'num6',
      color: 5,
    },
    {
      name: 'bass',
      sample: './audio/vinyl/bass.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num7',
      color: 6,
    },
    {
      name: 'shk',
      sample: './audio/vinyl/shk.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num8',
      color: 7,
    },
    {
      name: 'rim',
      sample: './audio/vinyl/rim.mp3',
      pitchMod: 0,
      lengthMod: 1,
      velocityMod: 1,
      key: 'num9',
      color: 8,
    },
  ],
};
