export const INIT_ONE_PATTERN = () => ({
  on: false,
  notes: [{ pitch: 24, velocity: 1, length: 1 }],
});

export const INIT_PATTERN = () => {
  const initPattern = [];
  for (let i = 0; i < 64; i++) {
    const initSounds = [];
    for (let i = 0; i < 9; i++) {
      initSounds.push(INIT_ONE_PATTERN());
    }
    initPattern.push({ sounds: initSounds, updated: 0 });
  }
  return initPattern;
};

export const init = {
  bpm: 128,
  instrument: null,
  pattern: INIT_PATTERN(),
};

export const analog = {
  bpm: 100,
  instrument: null,
  pattern: [
    {
      sounds: [
        { on: true, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        {
          on: true,
          notes: [
            { pitch: 24, velocity: 1, length: 1 },
            { pitch: 24, velocity: 1, length: 1 },
          ],
        },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: true, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
      ],
      updated: 0,
    },
    {
      sounds: [
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: true, notes: [{ pitch: 24, velocity: 0.5, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
      ],
      updated: 0,
    },
    {
      sounds: [
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: true, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
      ],
      updated: 0,
    },
    {
      sounds: [
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: true, notes: [{ pitch: 24, velocity: 0.5, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
      ],
      updated: 0,
    },
    {
      sounds: [
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: true, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
      ],
      updated: 0,
    },
    {
      sounds: [
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: true, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
      ],
      updated: 0,
    },
    {
      sounds: [
        { on: true, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: true, notes: [{ pitch: 24, velocity: 0.5, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
      ],
      updated: 0,
    },
    {
      sounds: [
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: true, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
      ],
      updated: 0,
    },
    {
      sounds: [
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        {
          on: true,
          notes: [
            { pitch: 24, velocity: 1, length: 1 },
            { pitch: 24, velocity: 1, length: 1 },
            { pitch: 24, velocity: 1, length: 1 },
          ],
        },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
      ],
      updated: 0,
    },
    {
      sounds: [
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: true, notes: [{ pitch: 24, velocity: 0.5, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
      ],
      updated: 0,
    },
    {
      sounds: [
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: true, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
      ],
      updated: 0,
    },
    {
      sounds: [
        { on: true, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: true, notes: [{ pitch: 24, velocity: 0.5, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
      ],
      updated: 0,
    },
    {
      sounds: [
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: true, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: true, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
      ],
      updated: 0,
    },
    {
      sounds: [
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: true, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
      ],
      updated: 0,
    },
    {
      sounds: [
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: true, notes: [{ pitch: 24, velocity: 0.5, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
      ],
      updated: 0,
    },
    {
      sounds: [
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: true, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
      ],
      updated: 0,
    },
    {
      sounds: [
        { on: true, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
      ],
      updated: 0,
    },
    {
      sounds: [
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: true, notes: [{ pitch: 24, velocity: 0.5, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
      ],
      updated: 0,
    },
    {
      sounds: [
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: true, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
      ],
      updated: 0,
    },
    {
      sounds: [
        { on: true, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: true, notes: [{ pitch: 24, velocity: 0.5, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
      ],
      updated: 0,
    },
    {
      sounds: [
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: true, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
      ],
      updated: 0,
    },
    {
      sounds: [
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: true, notes: [{ pitch: 24, velocity: 0.5, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
      ],
      updated: 0,
    },
    {
      sounds: [
        { on: true, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: true, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
      ],
      updated: 0,
    },
    {
      sounds: [
        { on: true, notes: [{ pitch: 24, velocity: 0.5, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: true, notes: [{ pitch: 24, velocity: 0.5, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
      ],
      updated: 0,
    },
    {
      sounds: [
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
      ],
      updated: 0,
    },
    {
      sounds: [
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: true, notes: [{ pitch: 24, velocity: 0.5, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
      ],
      updated: 0,
    },
    {
      sounds: [
        { on: true, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: true, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: true, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
      ],
      updated: 0,
    },
    {
      sounds: [
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: true, notes: [{ pitch: 24, velocity: 0.5, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
      ],
      updated: 0,
    },
    {
      sounds: [
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: true, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: true, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
      ],
      updated: 0,
    },
    {
      sounds: [
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: true, notes: [{ pitch: 24, velocity: 0.5, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
      ],
      updated: 0,
    },
    {
      sounds: [
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: true, notes: [{ pitch: 24, velocity: 0.5, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
      ],
      updated: 0,
    },
    {
      sounds: [
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: true, notes: [{ pitch: 24, velocity: 0.5, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
      ],
      updated: 0,
    },
    {
      sounds: [
        { on: true, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
      ],
      updated: 0,
    },
    {
      sounds: [
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: true, notes: [{ pitch: 24, velocity: 0.5, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
      ],
      updated: 0,
    },
    {
      sounds: [
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: true, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
      ],
      updated: 0,
    },
    {
      sounds: [
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: true, notes: [{ pitch: 24, velocity: 0.5, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
      ],
      updated: 0,
    },
    {
      sounds: [
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: true, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
      ],
      updated: 0,
    },
    {
      sounds: [
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: true, notes: [{ pitch: 24, velocity: 0.5, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
      ],
      updated: 0,
    },
    {
      sounds: [
        { on: true, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: true, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
      ],
      updated: 0,
    },
    {
      sounds: [
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: true, notes: [{ pitch: 24, velocity: 0.5, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
      ],
      updated: 0,
    },
    {
      sounds: [
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
      ],
      updated: 0,
    },
    {
      sounds: [
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: true, notes: [{ pitch: 24, velocity: 0.5, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
      ],
      updated: 0,
    },
    {
      sounds: [
        { on: true, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: true, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
      ],
      updated: 0,
    },
    {
      sounds: [
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: true, notes: [{ pitch: 24, velocity: 0.5, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
      ],
      updated: 0,
    },
    {
      sounds: [
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: true, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: true, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
      ],
      updated: 0,
    },
    {
      sounds: [
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: true, notes: [{ pitch: 24, velocity: 0.5, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
      ],
      updated: 0,
    },
    {
      sounds: [
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: true, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
      ],
      updated: 0,
    },
    {
      sounds: [
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: true, notes: [{ pitch: 24, velocity: 0.5, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
      ],
      updated: 0,
    },
    {
      sounds: [
        { on: true, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: true, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
      ],
      updated: 0,
    },
    {
      sounds: [
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: true, notes: [{ pitch: 24, velocity: 0.5, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: true, notes: [{ pitch: 24, velocity: 0.5, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
      ],
      updated: 0,
    },
    {
      sounds: [
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: true, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
      ],
      updated: 0,
    },
    {
      sounds: [
        { on: true, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: true, notes: [{ pitch: 24, velocity: 0.5, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: true, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
      ],
      updated: 0,
    },
    {
      sounds: [
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: true, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
      ],
      updated: 0,
    },
    {
      sounds: [
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: true, notes: [{ pitch: 24, velocity: 0.5, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: true, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
      ],
      updated: 0,
    },
    {
      sounds: [
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: true, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: true, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
      ],
      updated: 0,
    },
    {
      sounds: [
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: true, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: true, notes: [{ pitch: 24, velocity: 0.5, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: true, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
      ],
      updated: 0,
    },
    {
      sounds: [
        { on: true, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
      ],
      updated: 0,
    },
    {
      sounds: [
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: true, notes: [{ pitch: 24, velocity: 0.5, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: true, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
      ],
      updated: 0,
    },
    {
      sounds: [
        { on: true, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: true, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: true, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: true, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: true, notes: [{ pitch: 24, velocity: 0.5, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
      ],
      updated: 0,
    },
    {
      sounds: [
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: true, notes: [{ pitch: 24, velocity: 0.5, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: true, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
      ],
      updated: 0,
    },
    {
      sounds: [
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: true, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: true, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: true, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: true, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
      ],
      updated: 0,
    },
    {
      sounds: [
        { on: true, notes: [{ pitch: 24, velocity: 0.5, length: 1 }] },
        { on: true, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: true, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: true, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
      ],
      updated: 0,
    },
    {
      sounds: [
        { on: true, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: true, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: true, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: true, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: true, notes: [{ pitch: 24, velocity: 0.5, length: 1 }] },
        { on: true, notes: [{ pitch: 24, velocity: 0.5, length: 1 }] },
      ],
      updated: 0,
    },
    {
      sounds: [
        { on: true, notes: [{ pitch: 24, velocity: 0.5, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: true, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: false, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
        { on: true, notes: [{ pitch: 24, velocity: 1, length: 1 }] },
      ],
      updated: 0,
    },
  ],
};

export const house = {
  bpm: 120,
  instrument: null,
  pattern: [
    [1, 1, 0, 0, 0, 0, 1, 0, 0],
    [0, 0, 0, 0.5, 0, 0, 0, 0, 0],
    [0, 0, 0, 1, 1, 0, 0, 0, 0],
    [0, 0, 0, 0.5, 0, 0, 0, 0, 0],
    [0, 1, 0, 0, 0, 1, 0, 0, 0],
    [0, 0, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 0, 0.5, 1, 0, 0, 0, 0],
    [0, 0, 0, 1, 0, 0, 0, 0, 0],
    [0, 1, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0.5, 0, 0, 0, 0, 0],
    [1, 0, 0, 1, 1, 0, 0, 0, 0],
    [0, 0, 0, 0.5, 0, 0, 0, 0, 1],
    [0, 1, 1, 0, 0, 1, 0, 0, 0],
    [0, 0, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 0, 0.5, 1, 0, 0, 0, 0.5],
    [0, 0, 0, 1, 0, 0, 0, 0, 0],
    [0, 1, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0.5, 0, 0, 0, 0, 0],
    [0, 0, 0, 1, 1, 0, 0, 0, 0],
    [0, 0, 0, 0.5, 0, 0, 0, 0, 0],
    [0, 1, 0, 0, 0, 1, 0, 0, 0],
    [0, 0, 0, 0.5, 0, 0, 0, 0, 0],
    [0, 0, 0, 1, 1, 0, 0, 1, 0],
    [0, 0, 0, 0.5, 0, 0.5, 0, 0, 0],
    [0, 1, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0.5, 0, 0, 0, 0, 0],
    [1, 0, 0, 1, 1, 0, 1, 0, 0],
    [0, 0, 0, 0.5, 0, 0, 0, 0, 1],
    [0, 1, 1, 0, 0, 1, 0, 0, 0],
    [0, 0, 0, 0.5, 0, 0, 0, 0, 0],
    [0, 0, 0, 0.5, 1, 0, 0, 0, 0.5],
    [0, 0, 0, 0.5, 0, 0, 0, 0, 0],
    [1, 1, 0, 0, 0, 0, 1, 0, 0],
    [0, 0, 0, 0.5, 0, 0, 0, 0, 0],
    [0, 0, 0, 1, 1, 0, 0, 0, 0],
    [0, 0, 0, 0.5, 0, 0, 0, 0, 0],
    [0, 1, 0, 0, 0, 1, 0, 0, 0],
    [0, 0, 0, 0.5, 0, 0, 0, 0, 0],
    [0, 0, 0, 1, 1, 0, 0, 0, 0],
    [0, 0, 0, 0.5, 0, 0, 0, 0, 0],
    [0, 1, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0.5, 0, 0, 0, 0, 0],
    [1, 0, 0, 1, 1, 0, 0, 0, 0],
    [0, 0, 0, 0.5, 0, 0, 0, 0, 1],
    [0, 1, 1, 0, 0, 1, 0, 0, 0],
    [0, 0, 0, 0.5, 0, 0, 0, 0, 0],
    [0, 0, 0, 1, 1, 0, 0, 0, 0.5],
    [0, 0, 0, 0.5, 0, 0, 0, 0, 0],
    [0, 1, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0.5, 0, 0, 0, 0, 0],
    [0, 0, 0, 1, 1, 0, 0, 0, 0],
    [0, 0, 0, 0.5, 0, 0, 1, 0, 0],
    [0, 1, 0, 0, 0, 1, 0, 0, 0],
    [0, 0, 0, 0.5, 0, 0, 0, 0, 0],
    [0, 0, 0, 1, 1, 0, 1, 1, 0],
    [0, 0, 0, 0.5, 0, 0.5, 0.5, 0, 0],
    [0, 1, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0.5, 0, 0, 0, 0, 0],
    [1, 0, 0, 1, 1, 0, 1, 0, 0],
    [0, 0, 0, 0.5, 0, 0, 0, 0, 1],
    [0, 1, 1, 0, 0, 1, 0, 0, 0],
    [0, 0, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 0, 1, 1, 1, 0, 0, 0.5],
    [0, 0, 0, 1, 0, 0, 0, 0, 0],
  ],
};
export const lush = {
  bpm: 80,
  instrument: null,
  pattern: [
    [1, 1, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 1, 0, 1, 0, 0, 1],
    [0, 0, 0, 0.5, 0, 0, 0, 0, 0],
    [0, 1, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 0, 0.5, 0, 0, 0, 0, 0],
    [0, 0, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 1, 0.5, 0, 0, 0, 0, 0],
    [0, 1, 0, 1, 1, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 1, 0, 0, 0, 1, 1],
    [0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0],
    [1, 1, 0, 1, 0, 0, 1, 0, 0],
    [0, 0, 0, 0, 0, 0.5, 0, 0, 0],
    [0, 0, 0, 1, 0, 0, 1, 0, 0],
    [0, 0, 1, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 1, 0, 1, 1, 0, 1],
    [0, 0, 0, 0.5, 0, 0, 0.5, 0, 0],
    [0, 1, 0, 1, 0, 0, 1, 0, 0],
    [0, 0, 0, 0.5, 0, 0.5, 0.5, 0, 0],
    [0, 0, 0, 1, 0, 0, 1, 0, 0],
    [0, 0, 1, 0.5, 0, 0.5, 0.5, 0, 0],
    [0, 1, 0, 1, 1, 0, 1, 0, 0],
    [0, 0, 0, 0, 0, 0, 0.5, 0, 0],
    [0, 0, 0, 1, 0, 0, 1, 1, 1],
    [0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0],
    [1, 1, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 1, 0, 1, 0, 0, 1],
    [0, 0, 0, 0.5, 0, 0, 0, 0, 0],
    [0, 1, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 0, 0.5, 0, 0, 0, 0, 0],
    [0, 0, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 1, 0.5, 0, 0, 0, 0, 0],
    [0, 1, 0, 0, 1, 0, 0, 0, 0],
    [0, 0, 0, 0.5, 0, 0, 0, 0, 0],
    [0, 0, 0, 1, 0, 0, 0, 1, 1],
    [0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0],
    [1, 1, 0, 1, 0, 0, 1, 0, 0],
    [0, 0, 0, 0, 0, 0.5, 0, 0, 0],
    [0, 0, 0, 1, 0, 0, 1, 0, 0],
    [0, 1, 1, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 1, 0, 1, 1, 0, 1],
    [0, 0, 0, 0.5, 0, 0, 0.5, 0, 0],
    [0, 1, 0, 1, 0, 0.5, 1, 0, 0],
    [0, 0, 0, 0.5, 0, 0.5, 0.5, 0, 0],
    [0, 0, 0, 1, 0, 0, 1, 0, 0],
    [0, 0, 1, 0.5, 0, 0.5, 0.5, 0, 0],
    [0, 1, 0, 1, 1, 0, 1, 0, 0],
    [0, 0, 0, 0.5, 0, 0, 0.5, 0, 0],
    [0, 0, 0, 1, 0, 0, 1, 1, 1],
    [0, 0, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 0, 1, 0, 0, 0, 0, 0],
  ],
};

export const vinyl = {
  bpm: 90,
  instrument: null,
  pattern: [
    [1, 1, 0, 0, 0, 0, 0, 1, 0],
    [0, 0.5, 0, 0, 0, 0, 0, 0, 1],
    [0, 0, 0, 1, 0, 0, 0, 1, 0],
    [0, 1, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 1, 0, 0, 1],
    [0, 0, 0, 0, 0, 0, 0, 0.5, 0],
    [1, 0, 0, 1, 0, 0, 0, 0, 0],
    [0, 1, 0, 0, 0, 0, 0, 0.5, 1],
    [0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 1, 0, 0, 0, 0, 0, 1, 1],
    [1, 0, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 1, 0],
    [0, 0, 1, 0, 0, 1, 0, 0, 1],
    [0, 0, 0, 0, 0, 0, 0, 0.5, 0],
    [0, 0, 0, 1, 0, 0, 0, 1, 0],
    [0, 0, 0, 0, 0, 0, 0, 0.5, 0],
    [1, 1, 0, 0, 0, 0, 0, 1, 0],
    [0, 0.5, 0, 0, 0, 0, 0, 0, 1],
    [0, 0, 0, 1, 0, 0, 0, 1, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 1, 0, 0, 1],
    [0, 0, 0, 0, 0, 0, 0, 0.5, 0],
    [1, 0, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0.5, 1],
    [0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 1, 0, 0, 0, 0, 0, 1, 1],
    [1, 0, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 1, 0],
    [0, 0, 1, 0, 0, 1, 0, 0, 1],
    [0, 0, 0, 0, 0, 0, 0, 0.5, 0],
    [0, 0, 0, 1, 0, 0, 0, 1, 0],
    [0, 0, 0, 0, 0, 0, 0, 0.5, 0],
    [1, 1, 0, 0, 0, 0, 0, 0, 0],
    [0, 0.5, 0, 0, 0, 0, 0, 0, 1],
    [0, 0, 0, 1, 0, 0, 0, 0, 0],
    [0, 1, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 1, 0, 0, 1],
    [0, 0, 0, 0, 0, 0, 0, 0, 0],
    [1, 0, 0, 1, 0, 0, 0, 0, 0],
    [0, 1, 0, 0.5, 0, 0, 0, 0, 1],
    [0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0.5, 0, 0, 0, 0, 1],
    [0, 0, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 0, 0.5, 0, 0, 0, 0, 0],
    [0, 0, 1, 1, 0, 1, 0, 0, 1],
    [0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0],
    [1, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 1, 0, 0, 1],
    [0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 0, 0.5, 0, 0, 0, 0, 1],
    [0, 0, 0, 0, 0, 0, 0, 0, 1],
    [0, 0, 0, 0.5, 0, 0, 0, 0, 1],
    [1, 0, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 1, 0, 0, 1],
    [0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0],
  ],
};
